- .eslintrc.yml
- .prettierrc
eslintとprettierがセミコロンをつけないと怒るようにしました。
> [fix] セミコロンを必須化する

- package.json
- src/adaptor/message-proxy.ts
- src/adaptor/observable.ts
- src/adaptor/voice-room-proxy.ts
- src/server/index.ts
しれっと `package.json` の `scripts` を修正しています
> 完全に動作しない不具合の修正

- src/adaptor/transformer/index.ts
- src/adaptor/transformer/tuple.ts
> タプル関係のシステムの修正

- package.json
- src/service/difference-detector.test.ts
- src/service/difference-detector.ts
- yarn.lock
> 編集差分計算のバグの修正

- src/adaptor/random.ts
- src/adaptor/transformer/message-convert.ts
- src/service/command-message.ts
- src/service/index.ts
- src/service/judgement.test.ts
- src/service/judgement.ts
- src/service/kaere.test.ts
- src/service/party.test.ts
- src/service/typo-record.test.ts
> ***†HARACHO ONLINE JUDGEMENT SYSTEM†*** の追加

- src/adaptor/transformer/message-convert.ts
- src/service/bold-italic-cop.test.ts
- src/service/bold-italic-cop.ts
- src/service/index.ts
> Bold-Italic警察だ!!! ：Bold-Italic警察の追加

- .eslintrc.yml
- src/adaptor/discord-output.ts
- src/adaptor/discord-voice.ts
- src/adaptor/embed-convert.ts
- src/adaptor/message-proxy.ts
- src/adaptor/random.ts
- src/adaptor/transformer/bot-filter.ts
- src/adaptor/transformer/index.ts
- src/adaptor/transformer/message-convert.ts
- src/adaptor/transformer/tuple.ts
- src/adaptor/voice-room-proxy.ts
- src/model/reservation.ts
- src/server/index.ts
- src/service/index.ts
- src/service/judgement.test.ts
- src/service/kaere.test.ts
- src/service/kaere.ts
- src/service/party.test.ts
- src/service/party.ts
- src/service/typo-record.test.ts
- src/service/typo-record.ts
- src/service/voice-diff.test.ts
- src/service/voice-diff.ts
> `import` 周りのリファクタ

- src/adaptor/role-proxy.ts
- src/service/kawaemon-has-all-roles.test.ts
- src/service/kawaemon-has-all-roles.ts
> ロールメンションの使用による改善

- .github/labeler.yml
- .github/workflows/auto-labeler.yml
> create(actions): auto labeler

- .commitlintrc.json
- .github/dependabot.yml
- .github/workflows/changelog.yaml
- .github/workflows/release.yml
- .huskyrc.json
- .releaserc.json
- CHANGELOG.md
- package.json
- src/service/hukueki.test.ts
- src/service/hukueki.ts
> Release v1.5.0

- yarn.lock
dependabot がうまく動いていなかったぶんの補填です.
> chore: 依存関係の更新

- src/adaptor/transformer/bot-filter.ts
> fix: システムメッセージに反応しないようにフィルタを強化

- .github/workflows/release.yml
> ci: CHANGELOG 生成の置き換え

- .github/workflows/test-else.yml
> ci: test-else の緊急修正

- CONTRIBUTING.md
```
詳しくは [Jest のドキュメント](https://jestjs.io/ja/docs/getting-started) をご覧ください。
```
> docs: Jestのドキュメントへのリンクがぶっ壊れているので修正

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/custom-issue.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
> issue/pull request Templateを作成

- .github/workflows/coverage.yml
- package.json
**Issue:**
テストケース漏れなど簡単なミスが頻発した.
**Type of Change:**
CI ワークフローと npm スクリプトの追加.
**Cause of the Problem (問題の原因)**
テスト不足を定量的に測定できず, 既存技術で機械的に判別できるミスのカバーも全て人力で行っていた.
**Dealing with Problems (問題への対処)**
codecov の連携を追加し, コードカバレッジレポートを送信する CI ワークフローを追加した.
**Additional Information (追加情報)**
コードカバレッジを改善する PR が別途必要.
> ci: コードカバレッジ計測と codecov のセットアップ

- .github/workflows/coverage.yml
> ci: Hotfix on type

- src/service/hukueki.test.ts
- src/service/hukueki.ts
**Issue:** No Issue
**Type of Change:**
実行結果にあった邪魔な `て` を削除しました。
**Cause of the Problem (問題の原因)**
`てNった` の `て` で自由なえぬ構文遊びができないことがありました.
**Dealing with Problems (問題への対処)**
上記の問題を対処するため、 デフォルト実行結果から `て` を削除しました。
> feat: 邪魔な `て` を削除

- README.md
**Issue:** No Issue
**Type of Change:**
`README.md` に Codecov のbadgeを追加しました。
**Details of implementation (実施内容)**
Codecov のダッシュボードからコピーできるbadgeを追加
> docs: codecovのbadge追加

- src/runner/schedule.ts
- src/service/party.test.ts
- src/service/party.ts
**Issue: #167**
バグ修正, バグが発生する状況のテストケースの追加
時間経過を考慮したテストが抜けていた
#156 の修正内容を必要としており, そちらのマージ待ち
> fix: ゲリラ失敗時に登録を解除するように

- src/adaptor/transformer/message-convert.ts
- src/service/command-message.ts
- src/service/stfu.test.ts
- src/service/stfu.ts
**Discussion:** #198
`CommandMessage` および `SheriffCommand` への機能追加
削除処理を行った後に, リアクションを付与して応答するようにしてみました.
> feat: stfu にて削除後にリアクションするように変更

- .github/workflows/codeql-analysis.yml
CI の改善
Dependabot の依存関係の更新の PR などで, 実行する必要が無い「run codeql analysis」が最も時間がかかっており作業効率が悪かった.
`paths-ignore` を追加して, 不要な状況下での実行を無効化した.
- フォーマットされていないかったので, ついでにフォーマット.
- ログの警告にあったとおり, `autobuild` を `@v2` へ更新.
> ci: CodeQL 解析のワークフローの最適化

- .github/workflows/release.yml
CI ワークフローの変更差し戻し
手動リリースに関して中途半端な施策を行っていたため, それらを差し戻す変更です.
以下は関連する PR です.
- この施策の導入: #180
- この施策の現状への修正: #212
> ci: "on push tag" の差し戻し

- package.json
- yarn.lock
#236 と #238 が分かれていために失敗していたので, まとめました.
> chore: Bump discord.js packages

- package.json
- src/adaptor/message-proxy.ts
- src/adaptor/role-proxy.ts
- yarn.lock
依存関係の更新, コードの修正
- `pm2` を `devDependencies` から除去
- `typescript` などを最新のものへ更新
- 型解析の仕様変更によりトランスパイルエラーになるコードの修正
> fix: 依存関係の更新と微修正

- .eslintrc.yml
- src/model/reservation.test.ts
- src/model/reservation.ts
- src/server/index.ts
- src/service/index.ts
- src/service/judging.ts
- src/service/kaere.test.ts
- src/service/kaere.ts
- src/service/party.test.ts
- src/service/party.ts
リファクタ, lint ルールの変更
引数が多い関数を, オブジェクトの分割代入などによって 3 個以下にしました. また, `eslintrc` に `max-params` を `error` として追加し, 3 個より多い引数で lint エラーを起こすようにしました.
> refactor: 引数が多い記述のリファクタ

- package.json
- src/adaptor/version/fetch.ts
- src/server/index.ts
- src/service/index.ts
- src/service/version.ts
機能の新規追加
自動更新が成功したかどうかの確認などで, 現在起動してるボットのバージョンが何であるのか調べたいことがありました. 今まではこれをヘルプメッセージやコマンドの動作の変化などで確かめることがありましたが, 効率が悪いことでした.
MessageQuote のようにアクティビティに自身のバージョンを表示することも考えましたが, ひとまずはユーザ一覧を見に行かなくても確認できるコマンドとして実装することにしました.
- `version` コマンドを追加
この機能の単純さから, テストは不要と判断したため追加していません.
> feat: version コマンドを追加

- package.json
**Issue:** No Issue
`yarn setup` でpm2に実行してほしいJavaScriptファイル(コンパイル済み)が正しく指定されていない
pm2 に依存しているコマンドの削除
> chore: `yarn setup` の削除

- assets/emoji-seq.yaml
- package.json
- src/adaptor/emoji-seq-loader.ts
- src/adaptor/transformer/message-convert.ts
- src/model/emoji-seq.test.ts
- src/model/emoji-seq.ts
- src/server/index.ts
- src/service/emoji-seq-react.test.ts
- src/service/emoji-seq-react.ts
- src/service/index.ts
**Issue:** #285
新機能の追加
指定の正規表現パターンに反応して, 一連のリアクションを付与する機能を追加しました.
現在はあまり正規表現を活かした反応パターンがなく, パターン自体も少ないです. 追加したいときは `assets/emoji-seq.yaml` ファイルへ同様に追加していってください.
> feat: EmojiSeq の追加

- src/service/meme.test.ts
- src/service/meme.ts
コードの修正, リファクタ, テストの追加
少し不完全で読みにくかったコードを修正しつつリファクタしました. また, サニタイズ部分のテストを追加しました.
> fix: 不完全なサニタイズの修正

- assets/emoji-seq.yaml
- src/service/meme.test.ts
- src/service/meme.ts
- src/service/meme/web3.ts
新規追加(feat)
いちばんやさしいWeb3の教本のMEMEを追加します。
```
!web3 Web3
「いちばんやさしいWeb3の教本」 - インプレス 
```
> feat: いちばんやさしいWeb3の教本のMEMEを追加

- src/service/deletion-repeater.test.ts
- src/service/deletion-repeater.ts
- src/service/index.ts
close #250
**Issue:** #250
feat: メッセージの内容が正確に`!stfu`だった場合は当該メッセージを出さないようにした
既存の実装の仕様
当該コミットにおいて変更を加えた
当該コミット
N/A
> feat: avoid echo back when `!stfu` was deleted

- src/adaptor/discord/role.ts
- src/server/index.ts
- src/service/command.ts
- src/service/command/role-info.test.ts
- src/service/command/role-info.ts
close #353
機能の新規追加
`!roleinfo <ロール ID>` でその ID のロールの情報を取得し表示するコマンドを追加しました.
> feat: roleinfo コマンドの追加

- .github/workflows/release.yml
- Dockerfile
Dockerfile の修正, ワークフローの追記
リリース CI にて, 新バージョン発行後に Container Registry に Docker イメージを push する CI を組みました.
> ci: GitHub Container Registry のセットアップ

- .github/workflows/test-else.yml
- .github/workflows/test.yml
- README.md
もうすでに Jest を使っていないにも関わらず CI 名に Jest が使用されていました. 今後のテストの変更も考えて, Test の表記に統一しました.
CI の名前が変わるため, ブランチ保護の設定を修正する必要があるかもしれません.
> ci: Jest の部分を Test へ変更

- assets/emoji-seq.yaml
feat(`MESSAGE`)
複数の絵文字Seqを追加しました。
* カス→:ks:
* 雪、ゆき、ユキ→え？雪さん留年した？絵文字
* かわえ、かわえもん→かわえアンパンマン絵文字とかわえハンド（左）絵文字
* Docker→Docker絵文字
* Python→Pythonクソ絵文字
* しゅん、しゅんちゃん→しゅんちゃん絵文字
スマホからのコミットなので変にスペルチェックがかかっておかしくなったりしてると思われるため、リクチェンを飛ばす際はなるべくサジェスト付きでお願いします。
> feat: 複数の新しいEmoji Seqを追加

- .github/labels.yml
新規追加(GitHub)
OreOreBotにあったラベル「Need more Hibikiness」を追加します。
[追加の流れ](https://canary.discord.com/channels/683939861539192860/690909527461199922/1006905317923237958)
> chore: ラベル「need more hibkiness」の追加

- src/adaptor/discord/member-stats.ts
- src/model/create-timestamp.ts
- src/server/index.ts
- src/service/command.ts
- src/service/command/guild-info.test.ts
- src/service/command/guild-info.ts
- src/service/command/user-info.test.ts
- src/service/command/user-info.ts
close #382
close #317
新規追加
`!guildinfo` / `!serverinfo` で環境変数で定義されているギルドIDのギルドの情報を表示します。
> feat: ギルド情報参照コマンドの追加

- Dockerfile
Dockerfile の更新
`node:18-slim` に移行した際に忘れていたビルドの依存関係を更新しました.
> chore(deps): Docker イメージのビルド依存関係の更新

- Dockerfile
Dockerfile の修正
ffmpeg のインストール部分が間違っていたので修正しました.
Dockerfile が正常に動作することを検証する CI があってもいいかもしれません.
> build: Fix ffmpeg installation

- .github/workflows/dockerfilelint-else.yml
ワークフローの修正
else のワークフローは元のワークフローと同じ名前にしないと動作しないので直しました. レビューミスです.
> ci: else のワークフロー名の修正

- src/adaptor/proxy/middleware.ts
バグ修正のための機能追加
バグの再現性があまり無いため, とりあえず応急処置的な対策をしてみました.
> fix: 同じメッセージが編集されたかどうかのチェックを追加

- LICENSE
- package.json
修正
下記ファイルにて `merunno` (現: `m2en`)がAuthorとして指定されていたものをOrgの `approvers` として指定するようにしました。
- `package.json`
- `LICENCE`
> chore: 各種Authorの修正

- .github/labeler.yml
修正
#467 のときに修正を忘れていた自動ラベル付与の設定ファイルを修正しました。
> ci(fix): label name

- SECURITY.md
修正(更新)
セキュリティに関する報告に使用してもらう鍵を更新しました。
> chore: GPG鍵の更新

- src/service/command/dice.test.ts
- src/service/command/dice.ts
close #494 
feat:タイトル通り
`v`,`s`を受け付ける
> feat: Dice verbose 各ダイスの出目を詳細表示するオプションを追加

- README.md
- docker-compose.yml
新規追加、変更
OreOreBot2 のイメージを使い、Docker Composeで起動するための設定ファイル `docker-compose.yml` を追加しました。
https://docs.docker.com/compose/
また、`README.md` にて、Docker Composeで起動する手順なども軽く追加しています。
> chore: docker-compose.yml の追加

- SECURITY.md
- src/service/command/meme.test.ts
> docs: update to gpg key

- .github/actions/publish/action.yml
CI の修正
カスタムアクションのディレクトリ構造が間違っていて, 正常に動作していませんでした.
[ファイル名を `action.yml` にしたディレクトリを指定する必要がある](https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions) ので, そのように修正しました.
> ci: カスタムアクションのディレクトリ構造の修正

- .github/workflows/docker-image-scan.yml
ワークフローの修正
スキャン CI が正しく動作していないので微修正しています.
> ci: 動かないスキャン CI を修正

- release-please-config.json
close #627.
コンフィグファイルの追加
#627 に基づき, リリースの基点化を正常化させるためにコンフィグを追加します.
> chore: release-please のコンフィグを追加

- .github/workflows/release.yml
- release-please-config.json
close #627.
ワークフローの修正, 設定ファイルの追加/修正
#629 の変更が正しく動作しなかったため, その修正です.
> ci: release-please の manifest コマンドを使用するように切り替え

- release-please-config.json
close #627.
設定ファイルの修正
[`packages` の指定が無いと動かない](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile) ようなので追加しました.
> build: packages の指定を追加

- .github/actions/publish/action.yml
修正
プッシュに使うDocker Imageのタグが不正でリリースCIが落ちてしまう問題を修正しました。
> fix: Docker Image のタグが不正な問題を修正

- src/server/index.ts
バグの修正
PID 1 問題を解消するためのシグナルハンドラを追加し, Docker 上でこのプロセスをキルした場合でも正常に終了できるようにしました.
> fix: PID 1 問題のためのシグナルハンドラを追加

- .editorconfig
限界開発鯖には nvim, vscode , IDE では JetBrains IDE など色んな勢力が存在しています。
インテントなどは全て prettier で統一しているので問題はありませんが、 文字コードやファイルの最後に改行をいれるなど prettier では制御出来ていない部分を `.editorconfig` で統一したいと思います。
> chore: .editorconfig の追加

- src/service/command/meme/hukueki.ts
- src/service/command/meme/kenjou.ts
- src/service/command/meme/koume.ts
- src/service/command/meme/moeta.ts
- src/service/command/meme/takopi.ts
- src/service/command/meme/web3.ts
修正
`--help` フラグで表示されるヘルプの説明欄がヘルプに値しないミームがあったため、書き直しました。
> fix: Memeのヘルプに使われる説明欄の修正

- .github/ISSUE_TEMPLATE/bug_report.yml
修正
Yaml の構文エラーにより、フォームが生成されていなかったので修正しました。
> fix: Bug report のform configを修正

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
修正(GitHub Issue Form)
`render: Text` を設定していたのでコードブロックとして解答欄が生成されてしまいました。このプルリクエストでは該当の問題を修正します。
> chore: GitHub Issue Form で提出されたIssueがコードブロックで生成されてしまう問題を修正

- src/adaptor/discord/output.ts
- src/adaptor/embed-convert.ts
- src/server/index.ts
- src/service/command/ping.ts
- src/service/voice-diff.test.ts
- src/service/voice-diff.ts
close #675 
変更
reply, 通常送信に使われる埋め込みのカラーをパーソナルカラーに変更
> feat: 埋め込みカラーをパーソナルカラーに

- .github/actions/publish/action.yml
CI の修正
[ドキュメント](https://github.com/docker/build-push-action#usage) を読んだところ, タグの形式が間違っているようなので直しました
> ci: タグの形式の修正

- src/service/emoji-log.ts
型の修正
`EmojiLog` の第 1 引数の型は `EmojiEvent` となるべきですがなぜか `RoleEvent` 型になっていたので修正しました.
> fix: 引数の型を EmojiEvent に修正

- .github/actions/publish/action.yml
CI の修正
タグの指定が不十分でしたので, [`docker/metadata-action` のドキュメントの `tags` の節](https://github.com/docker/metadata-action#tags-input) に基づいて修正しました.
> ci: Docker イメージのタグを修正

- Procfile
ファイルの削除
使っていない Heroku の Procfile を削除しました.
> chore: Procfile の削除

- .eslintrc.yml
- package.json
- src/adaptor/discord/voice.ts
- src/adaptor/proxy/message.ts
- src/adaptor/proxy/middleware.ts
- src/adaptor/proxy/voice-room.ts
- src/model/command-schema.ts
- src/model/reservation.ts
- src/runner/message.ts
- src/runner/schedule.ts
- src/runner/voice-room.ts
- src/service/bold-italic-cop.ts
- src/service/command/command-message.ts
- src/service/command/dice.ts
- src/service/command/gyokuon.ts
- src/service/command/judging.ts
- src/service/command/kaere.ts
- src/service/command/party.ts
- src/service/command/stfu.ts
- src/service/command/typo-record.ts
- src/service/deletion-repeater.ts
- src/service/difference-detector.ts
- src/service/voice-connection.ts
- yarn.lock
lint ルールの追加, コメントの修正
これまでのドキュメントコメントは体裁がバラバラだったので, `eslint-plugin-tsdoc` を導入しました. それに伴ってルールに沿っていないドキュメントコメントを修正しました.
> doc: eslint-plugin-tsdoc の追加とドキュメントの修正

- src/service/command/meme.test.ts
- src/service/command/meme.ts
バグの修正, テストの追加
#749 のリファクタでエラーが 3 回出てしまうデグレードを起こしていました. そのためエラーが 1 回しか出ないように修正し, そのテストコードを追加しました.
> fix: エラーを一度しか出さないように修正

- .github/workflows/release.yml
> ci: リリース制御に非公開ボットアカウント higuchi-ichiyo を使用

- src/service/command/channel-info.test.ts
- src/service/command/channel-info.ts
新規追加
- チャンネル情報コマンドを引数なしで実装した際送信元のチャンネル情報を表示するようにしました。
> feat: チャンネル情報コマンドを引数なしで実装した際送信元のチャンネル情報を表示するように

- release-please-config.json
> ci: CHANGELOG.md のパスを修正

- .github/labeler.yml
- .github/workflows/auto-labeler.yml
`*` を使うにはシングルクォーテーションなどで囲う必要があったみたいです
> ci(fix): Auto Labeler のコンフィグを修正

- packages/bot/src/adaptor/proxy/command.ts
- packages/bot/src/runner/command.ts
- packages/bot/src/service/command.ts
- packages/bot/src/service/command/channel-info.ts
- packages/bot/src/service/command/command-message.ts
- packages/bot/src/service/command/debug.ts
- packages/bot/src/service/command/dice.ts
- packages/bot/src/service/command/guild-info.ts
- packages/bot/src/service/command/gyokuon.ts
- packages/bot/src/service/command/help.ts
- packages/bot/src/service/command/judging.ts
- packages/bot/src/service/command/kaere.ts
- packages/bot/src/service/command/kokusei-chousa.ts
- packages/bot/src/service/command/meme.ts
- packages/bot/src/service/command/party.ts
- packages/bot/src/service/command/ping.ts
- packages/bot/src/service/command/register.test.ts
- packages/bot/src/service/command/role-create.ts
- packages/bot/src/service/command/role-info.ts
- packages/bot/src/service/command/role-rank.ts
- packages/bot/src/service/command/stfu.ts
- packages/bot/src/service/command/typo-record.ts
- packages/bot/src/service/command/user-info.ts
- packages/bot/src/service/command/version.ts
リファクタ
runner モジュールのコードは他のモジュールのコードに依存性はいけないはずですが, `CommandRunner` はその定義が service モジュールのコードに依存していました. そのため, いくつかの `interface` を runner 側へ移するリファクタリングを行いました.
> refactor: CommandResponder を runner へ移動

- Dockerfile
- packages/bot/package.json
ビルドスクリプトの修正
手元で Docker イメージをビルドしてみても動かなかったので, 動くように修正しました.
> build: ES Modulesのためのビルド構成の修正

- .github/workflows/release.yml
CI の修正
#1200 にて, 勘違いして間違ったところまで変えていたのを差し戻しました.
> ci: Fix docker publish condition

- .github/labeler.yml
設定ファイルの修正
設定ファイルの破壊的変更で CI が動作しなくなっていたので, [actions/labeler](https://github.com/actions/labeler) のドキュメントを参考に修正しました.
> ci: any-glob-to-any-file を使用するように修正

- .github/workflows/publish.yml
- .github/workflows/release.yml
close #1148
- reusable workflowの書き方が誤っていたので修正
- workflow_dispatchによる手動releaseでもタグ名などを与えられるように
- publishにpermissionを明示
> ci: Publishワークフローの修正

- packages/docs/src/pages/development/emoji-seq.mdx
- packages/docs/src/pages/development/meme.mdx
- packages/docs/src/pages/development/running/index.mdx
> docs: update require environment info

- Dockerfile
- packages/bot/package.json
- packages/bot/src/server/index.ts
- pnpm-lock.yaml
> chore: sentry を有効化

- packages/docs/src/pages/references/commands/role-create.mdx
- packages/docs/src/pages/references/features/delete-diff.mdx
#1249 で追加された機能についてドキュメントを更新しました.
> docs: 早すぎるメッセージ削除だった場合の delete-diff に関してのドキュメント更新

- Dockerfile
- packages/bot/package.json
- packages/bot/src/server/index.ts
- pnpm-lock.yaml
Approvers Sentry が現在機能していない現状を踏まえ, Sentry SDK が依存しているパッケージを削除しました
> fix(docker): Sentry 依存のパッケージを削除

- packages/bot/src/service/welcome-message.test.ts
- packages/bot/src/service/welcome-message.ts
機能の変更, データの修正
ウェルカムメッセージの Getting Started がリンク切れしていたので, Notion に移行していたものへリンクを貼り直しました.
また, メンバー情報登録ウェブアプリへの誘導がちょっと不十分だったので, そこへのリンクを追加しました.
> feat: ウェルカムメッセージを更新する

- .github/workflows/release.yml
CI の修正
依存している GitHub Action パッケージのレポジトリの移管に対応し, その指定を修正しました.
> ci: Replace google-github-actions with googleapis

- .github/renovate.json
CI の修正
レビュアーなど古いまま更新されていなかった情報を更新しました.
> ci: Update renovate config

- packages/bot/src/service/command/meme/index.ts
- packages/bot/src/service/command/meme/procon32.ts
- packages/bot/src/service/command/meme/test/procon32.test.ts
> feat: Add procon32

- Dockerfile
CI の修正
bun.lock への移行に伴う lockfile の指定変更に対応.
> ci: Fix Dockerfile
