approvers/OreOreBot2

src/server/extract-env.ts
`.env` の指定を空にしてしまうと空文字列として認識してしまい設定ミスにつながるので, 空文字列を指定が無いものとして扱うようにしてみました.
=> extractEnv の改善

.github/workflows/eslint.yml, .github/workflows/prettier.yml, .github/workflows/test-else.yml
Markdown に対しても ESLint を使用しているので, Markdown を編集したときも CI を実行する動作が正しくなりました.
テストの場合は Markdown に対して実行することが無いのでジェネリックワークフローを用意して常に CI が通るようにしました.
=> ci: Markdown に関する CI の修正

src/service/kokusei-chousa.test.ts, src/service/kokusei-chousa.ts
- 国勢調査に **人間の数**(BOTユーザではない一般ユーザー) を追加
- 国勢調査の項目名を一部修正
- 国勢調査のEmbedの値の位置を改善
=> feat: 国勢調査に人間の数の項目名を追加、改善

src/service/judgement.test.ts, src/service/judgement.ts
=> fix: `judge` コマンドのケース数に上限を追加

.github/workflows/codeql-analysis.yml
https://github.com/approvers/OreOreBot2/runs/6186607446
Analysis結果が `Not found` になるのを直します
=> fix: CodeQL AnalysisがTypeScriptに対してのみ走るように

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/custom-issue.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/pull_request_template.md
**Issue:** #165 
**Type of Change:**
- テンプレートの各項目をヘッダー(`h3`)に変更
- Issue, Pull Requestの貢献について追記
**Cause of the Problem (問題の原因)**
現在の各テンプレートは項目と内容がごっちゃになりがちでわかりにくい問題がありました。
**Additional Information (追加情報)**
ものすごく小さい変更を該当PRで済ませました: 
- `README.md` であった虚偽の文章を削除
- ~~Herokuの設定ファイルを削除~~
- ~~スクリプトコマンド `yarn build`(コンパイル) を `yarn compile` に修正~~
=> docs: Issue / Pull Request Templateの修正

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml
**Issue:** No Issue
CIの修正
CodeQL CIで以下の警告が報告されていた:
> 1 issue was detected with this workflow: Using `on.push.paths-ignore` can prevent Code Scanning annotating new alerts in your pull requests.
これについて https://github.com/github/codeql-action/issues/283 ・ [Code Securityに関するGitHub Docs](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-a-custom-configuration-file) を見てみると GitHub Actions の設定ファイル(`workflows/` 配下) でパスの除外(paths-ignore)を行うのはベストプラクティスではないことがわかった
https://github.com/github/codeql-action/issues/283 を見ると [codeql-action](https://github.com/github/codeql-action) では独自の設定ファイルがあり、それを `jobs.steps.with.config-file` にパスとして渡してあげることで対処
- GitHub Actionsの設定ファイルから `on.push.paths-ignore` と …
=> ci: CodeQLの問題を修正

.github/workflows/release.yml
**Issue:** #140
Ci ワークフローの修正
リリースをあらゆる main への push にしていたためいくつかの弊害があった
リリース CI の実行条件を, `v*.*.*` の形式のタグが push されたときに変更しました.
これ以降, リリースするには以下のようにコマンドを実行するか, ほか git クライアントでタグを作成 & push することになります.
```sh
git tag v1.2.3
git push origin v1.2.3
```
=> ci: リリース CI の実行条件を修正

.github/workflows/release.yml
CI ワークフローの修正
リリース CI の実行条件を `cron` で毎週土曜日の正午 (YML 上の表記は UTC であることに注意) に変更しました. これによりデフォルトブランチの最後のコミットを用いて, 毎週リリースが自動作成されます.
`semantic-release` は差分を検知して変更が無いときはリリースを作成しないため, 空のリリースが作られることはありません.
=> ci: リリース CI の実行条件を schedule に変更

src/service/meme.test.ts, src/service/meme/dousurya.ts
潜在した破壊的変更の修正
#210 にて `dousureba` コマンドを `dousurya` に変更していましたが, その際に `dousureba` への対応を削除していたため破壊的変更となっていました. `dousurya` に加えて `dousureba` でも反応するように修正し, 破壊的変更を解消します.
=> fix: dousureba も dousurya として扱うように修正

.github/workflows/release.yml
CI の修正
`v*.*.*` の形式のタグを push する場合でも CI が動作するようにしていたが, この場合に CI でもタグを作成しようとしてしまうためリリースに失敗していた.
`semantic-release` の設定を変更して, 手動作成したタグをそのまま利用してリリースできるようにすることを考えた. しかし, この場合だと間違ったバージョンのタグを作成した場合に混乱が生じる. それだけでなく, 正しいバージョンのタグを発行する手間が生じる.
`latest` タグを `push` したときに実行するように条件を変更した. これにより, どの場合でも `semantic-release` によって正しいバージョンのタグとリリースが生成される.
この方法では, `latest` タグが既に存在している場合に以下の手順で上書きしなければならない.
1. このタグをローカルで更新する. `git tag -f latest`
2. タグを forced-push する. `git push -f origin latest`
=> ci: リリース CI のタグによる実行条件を `latest` に変更

src/service/typo-record.test.ts, src/service/typo-record.ts
**Issue:** #190
機能追加, 小さな仕様変更
`typo by <ユーザID>` で特定ユーザの今日の Typo リストも表示できるようにしました. それに伴い, 引数が多すぎる場合の専用ヘルプを追加しました.
ユーザ ID を用いて Embed メッセージ上でユーザ名解決のためにメンションしたのですが, これは `title` だと利用できませんでした. 元々のリスト表示を含リスト表示を全て `description` に統合しました.
=> feat: `typo by` コマンドの追加

src/service/kawaemon-has-all-roles.test.ts, src/service/kawaemon-has-all-roles.ts
#234 で追加した機能が Discord の仕様によって期待通りに動作しなかったため, 差し戻します.
=> fix: Revert "feat: 限界ポイントロールをかわえもんから自動で外すように (#234)"

src/adaptor/transformer/message-convert.ts, src/model/embed-message.ts, src/service/command-message.ts, src/service/help.ts
**Issue:** #256
機能の新規追加
Message Components を利用して実装した戻る/進むボタンを用いて, Embed メッセージのページめくりを実装しました. また, `help` コマンドにおいてこれを利用するように書き換えました.
=> feat: help コマンドをページめくりできるように

.github/dependabot.yml
**Issue:** #
新規追加, 変更
Dependabot version updateにて、GitHub Actions を監視対象エコシステムに追加し、使用している "アクション" に更新がある場合は Dependabot がPRを作成します。
これにより、どのエコシステムのPRなのかがわかるようにCommit Prefixで示すようにしました。
- `chore(npm)`: npmパッケージのアップデート
- `chore(ci)`: アクション(GitHub Action)のアップデート
今後作成される Dependabot version update のPRに @m2en , @MikuroXina をReviewersとしてDependabotが指定するようにしました。
=> chore: Dependabot version update - `GitHub Actions` を監視対象エコシステムに追加

.husky/pre-commit, package.json
コミットフックの修正, 依存関係の更新
[husky](https://typicode.github.io/husky/#/) のバージョンを自動更新した際に, WSL などの一部環境で pre-commit が動作しなくなっていました.
`npx husky-init` にを実行し, `.husky/pre-commit` を再生成して `husky` を `devDependencies` へと移動させました.
依存関係に対して dependabot が破壊的なバージョン更新を行う際に, そのままマージしてよいのかどうか検証するプロセスを検討すべきかもしれない.
=> chore: Husky ファイルのマイグレーション

.github/ISSUE_TEMPLATE/custom-issue.md, .github/pull_request_template.md
ドキュメント(テンプレート)の改善
プルリクエストのコンテキストに追加すると指定のIssue番号のIssueを自動でクローズする **"issue close keywords"** を追加しました。
参考: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
`.github/ISSUE_TEMPLATE/custom-issue.md` について、説明欄( `about` )が不適切だったため、その修正も加えています。
=> docs: issue close keywordを追加

src/service/meme.ts, src/service/meme/nigetane.ts
逃げたねコピペ構文の追加.
他のmemeの実装に従い, 逃げたねコピペ構文を生成する機能を追加しました.
見た目が思ってたのと違うかも知れません. あとArcaea勢への若干のネタバレの心配があります. 時事ネタなので.
=> feat: 逃げたねコピペ構文の追加

src/adaptor/discord/member-stats.ts, src/server/index.ts, src/service/index.ts, src/service/role-rank.test.ts, src/service/role-rank.ts
close #338.
機能の新規追加
`!rolerank` でロール数のランキングを表示する機能を追加しました. 各メンバーごとのロール数でソートし, 上位 5 名をランキング形式で表示します. ロール数が同じだった場合の処理, 表示する個数を指定できる機能などは実施していませんので, 必要であればお申し付けください.
=> feat: ロール数ランキングの追加

src/server/extract-env.ts
コードの修正
`extractEnv` の型付けが正しく動作しなくなっていたため修正しました. それに伴ってコードやコメントも少し変更しています.
=> fix: extractEnv の型の修正

README.md, src/server/index.ts
機能の新規追加, 環境変数の新規追加
`PREFIX` 環境変数によりコマンドの接頭辞をカスタマイズできる機能を追加しました.
テスト用に起動したボットの `PREFIX` を変えておくことで, 本来のボットを動かしつつテスト用のボットアカウントを実行してもコマンドが衝突しなくなります. それ以外の機能 (メッセージ削除への反応など) はまだ重複するので, そういった非コマンド機能を無効化できるようにする変更も予定しています.
=> feat: PREFIX 環境変数でボットの接頭辞を変えられるように

src/adaptor/proxy/transformer/message-convert.ts
コードのバグ修正
Discord.js のバージョン更新の際に, メッセージ本文が `null` の代わりに `''` になることがある仕様変更を確認していました. しかし, それに起因するバグが発生したため検知して弾くようにコードを修正しました.
=> fix: 空のメッセージに反応するバグを修正

src/adaptor/discord/sheriff.ts, src/service/command/stfu.test.ts, src/service/command/stfu.ts
Closes #347.
機能の新規追加
`!stfu 25`
のように削除個数を指定できるようになりました. 指定した回数分繰り返して実行したのと同じ扱いになります.
#347 で提案されていた探索範囲を指定できるようにする機能は, 大きくしすぎると予期しない古いメッセージの削除を招き, 小さくしすぎると全く削除できません. 少し使いづらいと判断して実装しませんでしたが, うまい活用方法やコマンド体系, 機能などがあればお申し付けください.
=> feat: stfu で削除個数を指定できるように

src/service/command/meme.test.ts, src/service/command/meme.ts, src/service/command/meme/moeta.ts
追加 ( `MEME` )
我慢できなかった
[雪親と雪自身のLINEからインスパイアを受けた構文](https://twitter.com/yuki_yuigishi/status/1555557259798687744) を追加します。
```
!moeta(or yuki) えぬ
「久留米の花火大会ね、寮から見れたの?」
「うん ついでにえぬが燃えた」
「は?」
```
=> feat: 燃えたmemeの追加

src/adaptor/discord/member-stats.ts, src/adaptor/discord/role.ts, src/adaptor/discord/voice.ts
コードの修正
discord.js のドキュメントにおいて [`Guild`](https://discord.js.org/#/docs/main/stable/class/Guild) を操作する前に [`available`](https://discord.js.org/#/docs/main/stable/class/Guild?scrollTo=available) フィールドを確認して利用可能かどうか確認することを推奨されていました. しかしコードにおいて確認を怠っていたため, その処理を追記しました.
=> fix: Guild の available フィールドを確認するように修正

.github/workflows/release.yml, .releaserc.json, package.json, yarn.lock
CI の修正
Docker パッケージのワークフローにおける publish が semantic-release とうまく連携できていませんでした. semantic-release のプラグインとして [`semantic-release-docker`](https://github.com/esatterwhite/semantic-release-docker) を導入し, Docker パッケージのリリースも semantic-release で行うようにしました.
=> ci: Docker のリリース部分の修正

.github/workflows/release.yml
close #397 
修正(CI)
[Release #84: Scheduled](https://github.com/approvers/OreOreBot2/actions/runs/2850598592) にて下記エラーが発生していました。
```shell
AggregateError: 
SemanticReleaseError: Docker authentication failed
at doLogin (/home/runner/work/OreOreBot2/OreOreBot2/node_modules/@codedependant/semantic-release-docker/lib/verify.js:79:21)
at verify (/home/runner/work/OreOreBot2/OreOreBot2/node_modules/@codedependant/semantic-release-docker/lib/verify.js:56:11)
at async validator (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
at async /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
at async /home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
at …
```
=> fix(ci): semantic-releaseのDocker認証エラーを修正

.github/dependabot.yml
小規模変更
dependabot version updatesの対象パッケージエコシステムに `docker` を追加し、Dependabotの監視下に追加します。
これにより、[Dockerfile](https://github.com/approvers/OreOreBot2/blob/main/Dockerfile) 内で使用しているイメージにアップデートがある場合はDependabotがプルリクエストを作成するようになります。
=> chore: dependabot version updatesの監視下にDockerのイメージを追加

src/service/command/version.ts
変更
`!version` で表示されるEmbedのデザインを変更しました。
**はらちょバージョン** をクリックすると [リリースページ](https://github.com/approvers/OreOreBot2/releases) へ移動し、**各バージョン** をクリックするとその該当のリリースページへ移動します。
=> feat: VersionEmbedのデザインを変更

src/server/index.ts, src/service/command.ts, src/service/command/role-rank.ts, src/service/kawaemon-has-all-roles.test.ts, tsconfig.json
tsconfig の変更
これまでコードレビューにおいて `import type` を指摘していましたが, これでは作業効率が少し悪くなっていました.
`tsconfig.json` にて `importsNotUsedAsValues` を `error` に設定し, 値を `import` していない場合の通常の `import` はエラーになるようにしました.
=> fix: importsNotUsedAsValues を error に変更

.github/workflows/license.yml, Dockerfile, README.md, package.json, yarn.lock
close #441.
GitHub Actions ワークフローの追加
`license-checker` を実行するワークフローを追加し, 問題のパッケージである `ffmpeg-static` を除去しました.
=> ci: ライセンスチェッカーの追加

.github/workflows/dockerfilelint-else.yml, .github/workflows/dockerfilelint.yml
close #444 
新規追加(CI)
#443 にて話題が上がったDockerfileの内容の検証を行うCIを追加しました。
Dockerfileが変更に上がっているプルリクエストに対し発動し、結果をプルリクエスト コメントに残します。
使用したWorkflowは [hadolint-action](https://github.com/hadolint/hadolint-action) です。
eslintのようなルール設定がこのhadolintでも可能です。ですが、走らせたことがないため、とりあえず今のところは様子見で、今後必要になったらコンフィグ設定を行おうと思います。
https://github.com/hadolint/hadolint#configure
=> ci: hadolintによるDockerfileのIint CIを追加

package.json
npm スクリプトの修正
以前にデバッグ実行のスクリプト名を `debug` から `dev` へと変更した際に, `predebug` を `predev` へと変更し忘れていたので修正しました.
=> fix: predebug を predev に名称変更

src/service/command/role-create.test.ts, src/service/command/role-create.ts
修正
`!rolecreate` で大文字のHEX(例: #FAAC9B)を指定した際、本来作成される処理が正しく実行されない問題を修正しました。
また、 `#` を指定しても作成される仕様なのに、ヘルプの埋め込みの記載が間違っていたのでそれも修正しています。
(`s/#はなしで指定してね`)
HEXが大文字・小文字、それぞれ追加した際のテストケースも同時に a89b69ec2c9b3464316d7ef44fbcd54afe54bbe0 で追加しています。
=> fix: 大文字のHEXを指定した際にロールが正しく作成できない問題の修正

.github/FANDING.yml
`.github/` 配下への設定ファイル追加
GitHub SponsorのSponsor Buttonを表示するための設定ファイルを追加します。
参考: [Displaying a sponsor button in your repository - GitHub Docs](https://docs.github.com/ja/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository)
@dependabot を除いた、過去に[OreOreBot2に貢献](https://github.com/approvers/OreOreBot2/graphs/contributors)し、かつGitHub Sponsorが有効になっている以下のメンバーのボタンを追加しています。
- @m2en 
- @shun-shobon 
GitHub Sponsorに限らず、他の同じようなサービスのリンクを表示することも可能です。
- [IssueHunt](https://issuehunt.io/)
- [Ko-fi](https://ko-fi.com/)
- [Liberapay](https://en.liberapay.com/)
- [Open Collective](https://opencollective.com/)
- [Otechie](https://otechie.com/)
- [Patreon](https://www.patreon.com/)
- 任意のリンク …
=> chore: GitHub Sponsorのボタンを表示するための設定ファイルを追加

.github/workflows/release.yml
CI の修正
実際のバージョンと `!version` が異なっていました. これは似たような前例から Docker パッケージのビルド時にタグを取得できていないことによるものと判断しました. そこでリリース CI で `fetch-depth: 0` を追記し, ブランチ/タグを全て取得するように変更しました.
=> ci: リリース時にタグを取得するように修正

Dockerfile
Dockerfile の修正
リリース CI でタグを生成した場合に, それを push しているだけで CI 側で読めていませんでした.
semantic-release-docker 側でビルド時に最新のタグの情報を渡してくれるので, これを使って手動で生成するようにしました.
ついでに RUN の一部が他の記述と同じスタイルになっていなかったので合わせています.
=> build: GIT_TAG 引数を用いてバージョンファイルを生成

src/adaptor/proxy/middleware/message-convert.ts, src/server/index.ts, src/service/deletion-repeater.test.ts, src/service/deletion-repeater.ts, src/service/difference-detector.test.ts, src/service/difference-detector.ts
close #484.
機能の新規追加
#484 およびその元になった #480 で議論された機能を実装しました.
リアクションでキャンセルする機能のために, メッセージリアクションのインテントを追加しています.
=> feat: diffと削除のメッセージを一定時間後に削除

.releaserc.json
close #492.
設定の修正
Docker イメージのビルド時に引数が渡っていなかったようなので, `dockerArgs` の指定を追加してみました.
=> build: dockerArgs の追加

src/service/command/meme.test.ts, src/service/command/meme/index.ts, src/service/command/meme/kenjou.ts
close #536 
新規追加
以下のコマンド形態を追加
```
!kenjou ホテルのオートロックの鍵は部屋に置きっぱなしにしないほうがいい
```
=> feat: 健常者エミュレータ構文の作成

src/service/command/guild-info.ts, src/service/command/role-info.test.ts, src/service/command/role-info.ts, src/service/command/user-info.ts
close #515 
新規追加
情報確認系のコマンドはとても長いため、実行しやすいように短縮したエイリアスを追加します。
今後この短縮形となる形のコマンドは追加されないと考え、プルリクエストを作成しました。(追加されたらまた考えます。)
- `!roleinfo` → `!role`
- `!guildinfo` → `!guild`
- `!userinfo` → `!user`
追加で、 `!guildinfo` (ギルド情報コマンド) 使用時表示されるタイムスタンプに **実行された日時までの経過時間** が表示されてなかったため、(共通のメソッドが使われていない) 置き換えました。
この変更により、Embed Objectのサイズがデカくなり、表示がおかしくなることを回避するため、タイムスタンプの表示部分を最後に移動しました。
=> feat: 短縮形エイリアスの追加

src/service/bold-italic-cop.ts
fix #574
fix
アスタリスク3つの列が2つ以上メッセージに含まれているかどうかを判定していたため、アスタリスク6つのみのケースでもマッチしていた
条件をアスタリスク3つの列で囲われた部分が1文字以上あるかどうかに変更した
同上
N/A
=> fix: アスタリスク6つのみのメッセージを無視

assets/emoji-seq.yaml
パターン設定ファイルの修正
「影響」や「カスタム」など日常的な言葉でよくマッチしてしまっていたので, 否定先読み/後読みを使ってマッチしにくくしました.
- `響` は直前に `影` がないときにマッチします
- `カス` は直前と直後にカタカナ `[ァ-ヴー]` がないときにマッチします
=> fix: 絵文字のマッチパターンをより厳格に

src/service/command/meme.ts
Meme の機能追加
`MemeTemplate` の `optionsKeys` に `c` などの一文字だけを使ったり `flagsKeys` に `verbose` などの 2 文字以上の文字列を指定しても正しく動作するようになりました.
#585 をより簡潔にするための機能です. なるべく早くレビューが欲しいです.
=> feat(meme): 短いオプションのキーが使えるように

.github/workflows/release.yml
CI ワークフローの修正
Release アクションが cron で動作しているので, フォークしたリポジトリでも動作していました.
暫定的な対処として, ジョブにリポジトリの一致条件を追加して, フォークしたリポジトリでは動作しないようにしました.
そもそもリリースを定期実行するのではなく, 定期的に「リリース PR」を作成し, それがマージされることでリリースを起動するようにしたほうがいいかもしれません. このほうが `package.json` のバージョンの不整合なども解消できます.
=> ci(release): レポジトリによる実行条件の追加

src/service/command/meme.test.ts, src/service/command/meme/takopi.ts
close #150 
タコピー構文にて、`-c`オプションで教員側の名称も任意にできる機能を追加しました。
- `-c` をオプション引数として実装
- オプションとフラグの同時使用に対応できるようにリファクタを行いました。 `-c -f`のように使用できます
=> feat: タコピー構文に教員名を変更できるオプション`-c`を追加

Dockerfile, package.json, src/adaptor/version/fetch.ts, tsconfig.json
Close #613.
コードの修正, ビルドスクリプトの修正
release-please の採用により `package.json` の `version` フィールドが最新バージョンを指すようになったため, バージョンの読み取りを `package.json` から行うようにしました.
また, 型検査の都合で `tsconfig.json` の `rootDir` を `.` に書き換えています.
=> fix: バージョンの読み取り先を `package.json` へ変更

src/adaptor/version/fetch.ts, tsconfig.json
コードの修正, 設定ファイルの修正
`dev` npm スクリプトにて使用している `ts-node` で動かなくなっていたので, import assertion を追記して `tsconfig.json` の `module` を `NodeNext` にしました.
=> fix: import assertion の追加

src/service/command/meme/index.ts, src/service/command/meme/ojaru.ts, src/service/command/meme/test/ojaru.test.ts
feat: あっぱれおじゃる様Bot[参考](https://twitter.com/DENBO_appare)の構文を一部再現できる機能を追加しました
動作例:
=> feat: あっぱれおじゃる様ミーム構文の追加

.github/workflows/docker-image-scan.yml
修正(CI)
ビルドとスキャンまで行う一連のワークフローの名称が `build docker image` になっていたので `Scan by Trivy` に修正し、意味が通るようにしました。
=> ci: Trivy Scan CIのWorkflow Nameを正常なものに修正

.github/actions/publish/action.yml
カスタムアクションの修正
タグから `v` の接頭辞が消えていたのを修正します.
=> build: 接頭辞 `v` を戻す

Dockerfile
Dockerfile の修正
Docker コンテナのビルド時に `tini` のコピーに失敗しているようなので, 一旦 `tini` を使わないように差し戻します.
=> fix(build): tini の差し戻し

.github/workflows/docker-image-scan.yml
修正
@dependabot のコミットは GitHub Actions の仕様上、 読み取り専用として動作するため Code Scanning の結果をアップロードすることができない。
そのため Trivy CI にてスキャンした結果をアップロードできず、CIが落ちてしまっていた。
上記問題を解決する案として以下のものがあげられたが、今回のエラーが推奨している方法で対処した
1. Workflowに書き込み権限を与える
2. @dependabot のブランチに対するプッシュは無視する
> Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, **please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches**. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.
@dependabot は依存関係アップデートの際 …
=> ci(fix): Dependabot のコミットに対する Trivy CI が失敗してしまう問題の修正

src/service/command/meme/index.ts, src/service/command/meme/nine.ts, src/service/command/meme/test/dousurya.test.ts, src/service/command/meme/test/nine.test.ts
新規追加
人は話し方が9割ジェネレーターを追加します。
```
!nine 限界開発鯖 オタク
限界開発鯖はオタクが9割
```
~~ついでにこのプルリクエストにどうすればのテストケースが重複していたので削除するコミットも追加しています。~~
=> feat: 人は話し方が9割ジェネレーターの追加

.github/renovate.json
#652 にて @mirror-kt に指摘された状態で Automerge が発動してしまい修正できずマージされてしまったため、このプルリクエストにて変更します。
なお、デフォルト値が再設定されていることについては現状 renovate 側から何も警告されていないので、今は特に気に留めず無視したいと思います。
=> chore: renovate のタイムゾーンを明確に

src/adaptor/proxy/command.ts, src/service/command/command-message.ts, src/service/command/help.ts
close #656
機能の追加, 仕様変更
`replyPages` 関数に `ReplyPagesOptions` 型のオプションオブジェクトの引数を追加しました. また, これを利用してヘルプコマンドのボタンをコマンド発行者しか押せないように修正しました.
=> fix: ヘルプコマンドのボタンをコマンド発行者しか押せないように修正

.github/actions/publish/action.yml
CI の修正
`ghcr.io` へログインするユーザ名を `github.actor`, つまりマージコミットした者に変更しました. また, Checkout や `yarn install` といった処理が不要だったので除去しました.
=> ci: `github.actor` を利用しつつ処理を単純化

src/service/command/version.ts
close #677 
修正( `!version` )
v1.30.0 ( #634 ) 以降、はらちょのタグには `oreorebot-` という文字列が最初につくようになっています。
`!version` を使うと埋め込みには [最新版のリリースページ](https://github.com/approvers/OreOreBot2/releases/latest) と そのビルドが運用しているバージョンのリリースページ へのリンクが埋め込みに表示されます。このリンクに使われるバージョン(タグ)の取得を行う `src/adaptor/fetch.ts` では package.json の `"version"` を取得していますが、 package.json には `oreorebot-` という文字列はついていないため、リンクが壊れて 404 になってしまっていました。
https://github.com/approvers/OreOreBot2/blob/ee078faa4b9fc9b4dc1d14a67628f1d544910d02/src/adaptor/version/fetch.ts#L4-L9
`src/adaptor/fetch.ts` でコンストラクタに渡す値に直接 `oreorebot2-` と文字列を埋め込もうとしましたが、 package.json から値を取得しているものに手を加えるのは適しているとは思わないので `src/service/command/version.ts` の埋め込みのプロパティに手を加えました。
https://github.com/approvers/OreOreBot2/blob/1dd349c9f7d607cbc721bc22b2ebd31a94629ec8/src/service/command/versio …
=> fix: break embed links displayed in `!version`

package.json, src/model/judging-status.ts, src/service/command/meme/ojaru.ts, src/service/command/meme/takopi.ts, src/service/command/party.ts, src/service/difference-detector.test.ts, src/service/difference-detector.ts, yarn.lock
close #665
機能の変更, 依存関係の更新
メッセージの変更差分を, 行ごとで変更があった箇所を強調表示する仕組みに変えました.
=> feat: メッセージの変更差分の改善

.github/workflows/invalid-character-checker-for-ntfs.yml
close #185
CI
NTFSがアスタリスクを含むファイル名でファイルを作成することを許可しないこと
アスタリスクを含むファイル名が検知されたら落ちるCIを導入
GitHub Actionsの追加
デバッグのためにファイル名の一覧を表示している
=> ci: 変更されたファイル名の中にアスタリスクが含まれていたら拒否する

.github/renovate.json
`platformAutomerge` を `true` にすることで GitHub の Auto-merge を利用するようにしました. また, `prConcurrentLimit` を 5 つにして, (セキュリティ関連を除いて) 同時に 5 つまでしか更新 PR が発生しないようにしました.
自動マージの際の Approve の問題は [Renovate Approve](https://github.com/apps/renovate-approve) を使えば解決できます. 既に導入リクエスト済みなので管理者の承認待ちです.
=> ci: Renovate の自動マージの設定を改善

.github/actions/publish/action.yml
Closes #701.
CI の修正
`docker/build-push-action` を `v4` に bump しました. あわせて v4 の利用ガイドに沿ってタグの管理やログイン部分を修正しました.
=> ci: Docker パッケージの作成 CI の修正

.github/actions/publish/action.yml
CI の修正
`ghcr.io` がついていないイメージを指定すると Docker Hub に push してしまうようなので, `images` から除去しました.
=> ci: 不正なイメージ名の除去

.github/FUNDING.yml, src/service/command/meme/index.ts, src/service/command/meme/syakai.ts, src/service/command/meme/test/syakai.test.ts
新規追加 (MEME)
@su8ru が times であげていたコードを勝手にMEME化しました。ちゃんと草は彼にあげます。
`!syakai Rust採用` >> `「首相、Rust採用に否定的な考え ― 『社会が変わってしまう』」`
=> feat: 首相の否定的な考えMEMEを追加

Dockerfile
Dockerfile の修正
Docker イメージのビルド時に husky が見つからないエラーが発生してしまうので, CI での `husky install` のスクリプトを [`pinst`](https://www.npmjs.com/package/pinst) で無効化するようにしました.
=> build: pinst を用いた husky install の無効化

.dockerignore, Dockerfile
Close #722.
Dockerfile の修正
以前の修正で `node_modules` がコピーされなくなっていたので修正しました. また, `.dockerignore` に `.yarn` の部分を追記しました.
=> build: Dockerfile の修正

src/service/difference-detector.test.ts, src/service/difference-detector.ts
コードの修正, テストの追加
以前に編集差分の検知機能を改善した際に, 差分が検知できない場合の文字列の状況が変わっていました.
生成した差分文字列が編集前と同じならば, メッセージを送信しないように修正しました.
=> fix: 空の編集イベントに反応しないように修正

src/service/command/meme/failure.ts, src/service/command/meme/index.ts, src/service/command/meme/test/failure.test.ts
新規追加 (MEME)
@KisaragiEffective が提案した MEME を追加します。ちゃんと草は彼にあげます。(いつもの)
```
!failure 想定している範囲内で止まることは、失敗と言い難い
「想定している範囲内で止まることは、失敗と言い難い」
「わかりました。それは一般に失敗と言います、ありがとうございます」
```
=> feat: 共同通信の記者MEME の追加

src/service/command/meme/failure.ts, src/service/command/meme/test/failure.test.ts
新規追加(MEME Option)
共同通信記者の失礼発言に含まれる **"失敗"** の部分を自由に変更できるオプション `-k` を追加します。
なお、オプションを含めない場合は通常の失礼発言になります。
```
!fail -k クラスのマドンナが好きなのにいじめてしまいました。 恋
「クラスのマドンナが好きなのにいじめてしまいました。」
「わかりました。それは一般に恋と言います、ありがとうございます」
```
=> feat: 共同通信記者の発言の "失敗" の部分を変えられるオプションを追加

assets/time-signal.yaml, package.json, src/adaptor/clock.ts, src/adaptor/proxy/middleware/message-convert.ts, src/adaptor/signal-schedule.ts, src/runner/schedule.ts, src/server/index.ts, src/service/time-signal.test.ts, src/service/time-signal.ts, yarn.lock
Close #17.
機能の追加, テストの追加
#17 で提案していたものを追加しました. 時報スケジュールは `assets/time-signal.yaml` ファイルで 3 パターンを必ず指定するようになっており, 以下のような形式になっています.
```yaml
MORNING: # キーはこの 3 パターンがすべて必須
time:
hours: 7   # 0 - 23 の数値
minutes: 0 # 0 - 59 の数値
message: 'マルナナマルマル、朝だ。…司令官、まだ寝てるの？'
NOON:
time:
hours: 12
minutes: 0
message: 'Полдень. 今日は何を作ってるんだい？'
MIDNIGHT:
time:
hours: 2
minutes: 0
message: 'マルフタマルマル、もう遅いね。眠かったらどうぞ。私の膝を貸そうか。'
```
=> feat: 新時報システムの追加

src/adaptor/discord/channel.ts, src/model/channel.ts, src/service/command/channel-info.test.ts, src/service/command/channel-info.ts
close #758
リファクタリング
`!channel` で表示されるチャンネル情報に含まれる一部の情報には不要なものが含まれます。 (cf. #758 )
一般メンバーには不要なフィールドを削除し、見通しを改善しました。
=> refactor: チャンネル情報の不要なフィールドを削除

src/service/command/meme/kenjou.ts, src/service/command/meme/test/kenjou.test.ts
close #759 
修正
`!kenjou --help` で表示される健常者エミュレーターWikiのURLを新しいものに置き換えました。
=> fix: 健常者エミュレーターWikiのURLを新しいWikiに置き換え

.github/CONTRIBUTING.md, SECURITY.md
修正(ドキュメント)
Security Policy と Contributing Guide ともに記述されている **セキュリティーに関する不具合の報告** にて２つの間に齟齬が見られているので修正しました。
----
- Contributing Guide 側には GitHub Security Advisories からの報告方法が書いてあるが、 Security Policy 側には記述がない
=> fix(docs): inconsistency between Security Policy and Contributing Guide

package.json, vitest.config.ts, yarn.lock
依存関係の更新, テストの設定の更新
`@vitest/coverage-c8` が非推奨となり, 代わりに `@vitest/coverage-v8` を使うことが推奨されたため移行しました.
=> chore(test): Migrate coverage to @vitest/coverage-v8

Dockerfile
Dockerfile の修正
`node:20-slim` の suite が更新された影響で利用可能な Python のバージョンが変わったので, インストールするバージョンを更新しました.
=> build(docker): Bump python3 version

src/adaptor/discord/member-stats.ts, src/service/command/user-info.test.ts, src/service/command/user-info.ts
close #914 
新規追加 (既存機能の変更)
Discord の新ユーザーネームシステムに対応しました。 ( `#` による識別タグが廃止されたシステム)
- 新システムに移行済みのユーザーはユーザーネームの最後に `#0` が付与された状態で Discord API が応答します。そのため、その `#0` を取り除く形で対応しました。
- 未変更のユーザー、新システム移行が始まっていないBot はまだ識別タグがあるためそのようなユーザー、Botに対して検索を実行した場合識別タグを今まで通り表示します。
- 埋め込み(Embed)のフィールド名は `ユーザーネーム` に統一しました。
- テストケースは識別タグを取り除かないパターン (識別タグがまだあるユーザーに対しての検索)を新しく追加しています。
=> feat: Discord の新ユーザーネームシステムに対応する

src/adaptor/discord/member-stats.ts, src/service/command/user-info.test.ts, src/service/command/user-info.ts
新規追加
- `!userinfo` ( `!user` ) で表示されるユーザー情報に新しくアバター画像をサポートしました。
- ギルド別のアバター画像が設定されている場合はその画像を表示し、設定されていない場合はユーザーのアバター画像を表示します。 (常に優先されて表示されるのはギルド別のアバター画像です。)
- アバター画像が設定されていない場合は初期設定のアバター画像が表示されます。 ( djs から提供されるURL)
=> feat: ユーザー情報としてユーザーのアバターをサポートするように

src/adaptor/discord/voice.ts, src/service/command/gyokuon.ts, src/service/command/kaere.ts, src/service/command/party.ts, src/service/voice-connection.ts
close #958
音声接続処理の仕様変更
切断時のハンドラが再接続すべきかどうかの判断を兼ねていましたが, これは再接続できるかもしれない状況で呼び出されるので, 強制切断された際には呼び出されていませんでした.
そもそも再接続することが好ましくないことが多く, ハンドラに機能を持たせすぎていたので, この再接続を制御する機能を除去し, あらゆる切断された状況でもハンドラが呼び出されるようにしました.
`VoiceConnection` の引数の仕様を変更し, それを利用していたコードの記述を修正しました. そして再接続処理のコードをすべて除去しました.
=> fix: 再接続の制御を除去

src/adaptor/proxy/command/slash.test.ts, src/adaptor/proxy/command/slash.ts
Resolves #978.
バグの修正
選択肢のオプション `CHOICES` だったときのパース結果が選択肢のインデックスになっておらず, 選択した値そのものになっていました.
正しくは選択した値が何番目かを取り出すようにすべきだったので, そのように修正しました.
=> fix: 選択肢のパース処理の修正

package.json
ビルド方法の変更
現在このプロジェクトではESBuildを用いてビルドを行っていますが，ビルドオプションが最適ではなく，ファイルサイズが増加していました．
上記の問題に対処するためにビルドオプションをいくつか追加し，最適なサイズのファイルが生成されるようにしました．
これにより140kBほどだったコードが71kBに縮小されました．
- `--minify`の追加．これはコードをMinifyするようになります．
- `--charset=utf8`の追加．これはUTF-8のコードポイントをエスケープしなくなります．今まではASCIIの範囲に収まらない場合は`\uXXXX`の形式でエスケープされていました．
`--charset=utf8`を追加する場合，そのコードが確実にUTF-8として解釈される必要があります．
[ESBuildのcharsetに関するドキュメント](https://esbuild.github.io/api/#charset)
=> build: ビルドされたコードの縮小

.github/FUNDING.yml
- GitHub Sponsors のボタンに表示するユーザーリストに新しく `approvers` を追加しました.
=> chore: GitHub Sponsors の設定ファイルに限界開発鯖Orgを指定する

compose.yaml, docker-compose.yml
2023年7月以降, Docker Compose v1 ( `docker-compose.yml` などが設定ファイルとなる Compose バージョン) は廃止され非推奨になりました. (セキュリティアップデートも降ってきません.)
それに伴いリポジトリ内の `docker-compose.yml` と `compose.yaml` に変更し, Docker Compose v2 に移行しました.
これに伴い Docker Compose v1 への後方互換性を実質的に破壊することになります.
参考: [Docker Compose release notes - docker docs](https://docs.docker.com/compose/release-notes/)
=> chore: 設定ファイルを Docker Compose v2 へ移行

release-please-config.json
#1058 マージ後, `changelog-path` が不正だったためそれを修正しました.
=> ci: CHANGELOG.md へのパスを修正

release-please-config.json
#1065 で削除した `last-release-sha` フィールドですが, 正しくリリース戦略を決めることが出来ていないようなので再び指定します.
=> ci last-release-sha フィールドを指定

packages/bot/src/service/command/version.ts
v1.47.0 の強制リリース後, GitのTagがかわってしまい `/version` で表示される埋め込みのURLが無効になっていたので修正.
=> fix: バージョンコマンドで使用されるリリースへのURLを修正

.github/workflows/release.yml
Step の実行条件を修正してみました. これで動くはずです.
=> ci(fix): リリースPRマージ後のCIで "Publish the Docker package" が実行されない問題の修正

packages/docs/theme.config.tsx
#1056 により, ページ編集ボタンのリンクが古いものになっていたので新しいものに変更しました. また直接編集ページに行けるようにしています.
=> docs: ページ編集ボタンのリンクを新しいものに変更する

packages/docs/src/pages/references/commands/voice/party.mdx
[`PATATO` -> `POTATO`](https://haracho.approvers.dev/references/commands/voice/party#%E3%81%AF%E3%82%89%E3%81%A1%E3%82%87%E3%81%8C%E6%8F%90%E4%BE%9B%E3%81%99%E3%82%8B-bgm) でした.
=> docs(fix): 間違っているパーティーのBGM IDを修正

packages/docs/theme.config.tsx
close #1087
設定の修正
ロゴ画像のパスが相対パスになっており, 最初に開いたページによってはパス解決に失敗していました.
画像のパスを絶対パスへと変更しました.
=> fix: ロゴ画像のパスを修正

.github/workflows/build.yml
close #1108.
CI の変更
docs 配下のファイルのハッシュをキャッシュのキーとして, Next.js のビルド成果物をキャッシュするようにしました.
=> ci: docsのビルドをキャッシュ

.github/workflows/release.yml
close #1148 
~~`release-please` が受け渡すタグ値が不正な問題について `steps.release.outputs.releases_created` から値を受け渡してもらえるようにしてみました. 直るかどうかはもう知りません.~~
v4 では `steps.release.outputs.releases_created` で不具合が起きているようです. 一度上の変更は取り消して if式 を修正してみました. 直るかどうかはもう知りません.
See also: https://github.com/google-github-actions/release-please-action/issues/912
=> fix(ci): fix problem with incorrect tagValue passed by release-please

.github/workflows/publish.yml
close #1224.
GitHub Action の修正
今まで `main` ブランチの `HEAD` を利用してイメージを作成していたのを, `inputs.sha` のコミットを参照して作成するように変更しました.
=> ci: publish の checkout に ref オプションを追加して inputs.sha を指定

Dockerfile
close #1227.
Dockerfile の修正
bot ワークスペースがスクリプト実行後に生成するビルド成果物の配置場所が間違っていました. 正しい位置にコピーするように修正し, その変更した位置のスクリプトを起動するように変更しました.
=> build: bot の workspace のビルド成果物の展開と起動を修正

Dockerfile
close #1229.
Dockerfile の修正
ワーキングディレクトリが変化したために動作しなくなっていたので, WORKDIR で改めて指定するようにしました. もっといいやり方があるかもしれません.
=> build: bot パッケージのディレクトリを WORKDIR に指定

packages/docs/src/pages/references/commands/voice/kaere.mdx, packages/docs/src/pages/references/commands/voice/party.mdx
#1111 で追加された `/kaere start` ・ `/party start` に関する注記の追加
=> docs: `/kaere` ・ `/party` での即時実行に関する注記追加

packages/bot/src/adaptor/proxy/middleware/message-convert.ts, packages/bot/src/server/index.ts, packages/bot/src/service/deletion-repeater.test.ts, packages/bot/src/service/deletion-repeater.ts, packages/bot/src/service/index.ts
close #1247
- feat(interface)!: `DeletionObservable`インターフェイスへの破壊的変更
- fix(type)!: `DeletionObservable`の変更に起因する型エラーの修正
- fix(test)!: `DeletionObservable`の変更に起因するテストケースのエラーを修正
- feat: メッセージを変化させるロジックを追加
- test: 追加したロジックのテストケースを追加
実装したい機能を実現するために必要なフィールドを追加しました。このために発生したエラーを修正しました。
特殊メッセージを送信する条件を満たしているかを確認し、満たしている場合メッセージを切り替える処理を追加しました。また、特殊メッセージを送信する条件を満たしたときにメッセージが切り替わっていることを確認するテストを追加しました。
=> feat: メッセージが投稿後３秒以内に削除された場合に特殊メッセージを送信するように変更

.github/CONTRIBUTING.md, packages/bot/README.md, packages/bot/package.json
OreOreBot2 がサポートする Node.js バージョンを v20 (現行の最新 LTS) に固定しました.
=> chore: サポートする Node.js のバージョンを `v20` に固定

packages/bot/package.json, pnpm-lock.yaml
スクリプトの修正, 依存関係の追加と削除
Node v20 に移行したときから ts-node がうまく動作しなくなっているために, デバッグ実行のスクリプトが使えなくなっていました.
代替として, ある程度実績がある TypeScript ランタイムの [tsx](https://github.com/privatenumber/tsx) を採用しこれに置き換えました.
軽く試してみて動作することは確認できましたが, ランタイムの変更によるデバッグ実行時の差異が現れるかもしれません.
=> chore: ts-node を tsx へ置き換え

Dockerfile
Dockerfile の修正
[リリース CI のエラーログ](https://github.com/approvers/OreOreBot2/actions/runs/7772156166/job/21194261789) に基づいて, apt パッケージのバージョン指定を修正しました. ローカルで `docker build -t oreorebot2 .` が通ることは確認しています.
=> fix(docker): apt パッケージのバージョン指定を修正

packages/bot/src/server/index.ts
バグ修正
依存関係レジストリにコマンドランナーを追加し忘れていた. ヘルプコマンドが他のコマンドを取得するためにコマンドランナーにアクセスしていたが, そこでの参照の解決に失敗して異常終了していた.
=> fix: Add command runner into registry

Dockerfile
Dockerfile の修正
Bun が semver へ厳密に従っておらずロックファイルの生成結果が整合しなくなることがあった. ベースイメージのバージョンがメジャーバージョンのみだったが, この問題への対処としてバージョン指定をパッチまで固定した.
=> fix: Fix bun version of base image

packages/bot/src/service/command/register.ts
Closes #1343.
機能の改善
登録済コマンドが更新されているかどうかの判定関数を, 少し丁寧に実装することで条件を厳しくした.
=> feat: Improve condition of updating commands
